#rebind prefix
unbind C-Space
set -g prefix C-Space

# Reload Config
bind r source-file "$XDG_CONFIG_HOME/tmux/tmux.conf" \; display "tmux config reloaded"

# Mouse
set -g mouse on

# Set cursor
set -as terminal-overrides '*:Se=\e[1 q'
